#!/bin/bash
# No es fa servir aquest codi.
# Lets Encrypt
# if [ -z "$WEBROOT" ] || [ -z "$GIT_EMAIL" ] || [ -z "$DOMAIN" ]; then
#  echo "You need the \$WEBROOT, \$GIT_EMAIL and the \$DOMAIN Variables"
# else
#  rm /etc/nginx/sites-enabled/default-ssl.conf
#  supervisorctl restart nginx
#  certbot --nginx certonly --webroot -w $WEBROOT -d $DOMAIN --email $GIT_EMAIL --non-interactive --agree-tos
#  ln -s /etc/nginx/sites-available/default-ssl.conf /etc/nginx/sites-enabled/
#
#  sed -i "s/##DOMAIN##/${DOMAIN}/g" /etc/nginx/sites-enabled/default-ssl.conf
#
#  supervisorctl restart nginx
#  echo "Letsencrypt ok. Restart nginx ok."
# fi
