version: '2'

networks:
    new:

services:
    nginx:
        build: ./docker_nginx
        environment:
            DOMAIN: "todevise.com"
            GIT_EMAIL: "eduard.dr@coditramuntana.com"
            WEBROOT: "/var/www/html/web"
        command: bash -c "cd /var/www/html && ./yii mongodb-migrate --interactive=0 && /start.sh"
        ports:
            - "8443:8443"
            - "8080:8080"
            # ONLY SERVER AFTER CAP DEPLOY - "443:8443"
            # ONLY SERVER AFTER CAP DEPLOY - "80:8080"
        volumes:
            - .:/var/www/html/
            # ONLY SERVER AFTER CAP DEPLOY - ./shared/system/vendor/:/var/www/html/vendor/
            # ONLY SERVER AFTER CAP DEPLOY - ./shared/system/runtime/:/var/www/html/runtime/
            # ONLY SERVER AFTER CAP DEPLOY - ./shared/public/web/assets/:/var/www/html/web/assets/
            # ONLY SERVER AFTER CAP DEPLOY - ./shared/public/images/uploads/:/var/www/html/web/uploads/
            # ONLY SERVER AFTER CAP DEPLOY - ./shared/public/thumbor_cache/:/var/www/html/thumbor_cache/
            # ONLY SERVER AFTER CAP DEPLOY - ./shared/public/thumbor_resized/:/var/www/html/thumbor_resized/
            # ONLY SERVER AFTER CAP DEPLOY - ./shared/.env:/var/www/html/.env
        networks:
            - new
        depends_on:
            - redis
            - mongo
            - thumbor
        links:
            - redis
            - mongo
    redis:
        image: redis
        networks:
            new:
                aliases:
                    - redis.todevise.com
                    - redis-session.todevise.com
                    - redis-cache.todevise.com
        expose:
            - "6379"
    mongodata:
        image: mongo:3.2
        volumes:
            - /data/db
            - /data/configdb
        command: --break-mongo
    mongo:
        build: ./docker_mongo
        volumes_from:
            - mongodata
        networks:
            new:
                aliases:
                    - ddbb.todevise.com
        expose:
            - "27017"
        ports:
            - "27017:27017"
    thumbor:
        image: apsl/thumbor:6.1.2
        volumes:
            - ./web:/images
            - ./thumbor_cache:/images_cache
            - ./thumbor_resized:/images_resized
            # ONLY SERVER AFTER CAP DEPLOY - ./shared/public/images/:/images/
            # ONLY SERVER AFTER CAP DEPLOY - ./shared/public/thumbor_cache/:/images_cache/
            # ONLY SERVER AFTER CAP DEPLOY - ./shared/public/thumbor_resized/:/images_resized/
        networks:
            new:
                aliases:
                    - thumbor.todevise.com
                    # ONLY PRODUCTION SERVER - img.todevise.com
        ports:
            - "8000:8000"
        environment:
            MAX_AGE: "604800"
            ALLOW_UNSAFE_URL: "True"
            SECURITY_KEY: "ccpXNPgnXHaONlWlzXTEGg458K9HfE"
            LOADER: "thumbor.loaders.file_loader"
            FILE_LOADER_ROOT_PATH: "/images"
            FILE_STORAGE_ROOT_PATH: "/images_cache"
            RESULT_STORAGE_FILE_STORAGE_ROOT_PATH: "/images_resized"
            RESULT_STORAGE_STORES_UNSAFE: "True"
