version: '2'

networks:
    new:

services:
    nginx:
        build: ./docker_nginx
        environment:
            DEV: "1"
            DOMAIN: "todevise.com"
            GIT_EMAIL: "alexandernst@gmail.com"
            WEBROOT: "/var/www/html/web"
            THUMBOR_SECURITY_KEY: "ccpXNPgnXHaONlWlzXTEGg458K9HfE"
            THUMBOR_SERVER: "thumbor.todevise.com:8000"
        command: bash -c "cd /var/www/html && composer install -v --prefer-dist && ./yii mongodb-migrate --interactive=0 && /start.sh"
        ports:
            - "8443:8443"
            - "8080:8080"
        volumes:
            - .:/var/www/html/
        networks:
            - new
        depends_on:
            - redis
            - mongo
            - thumbor
        links:
            - redis
            - mongo
    redis:
        image: redis
        networks:
            new:
                aliases:
                    - redis.todevise.com
                    - redis-session.todevise.com
                    - redis-cache.todevise.com
        expose:
            - "6379"
    mongodata:
        image: mongo:3.2
        volumes:
            - /data/db
            - /data/configdb
        command: --break-mongo
    mongo:
        build: ./docker_mongo
        volumes_from:
            - mongodata
        networks:
            new:
                aliases:
                    - ddbb.todevise.com
        expose:
            - "27017"
        ports:
            - "27017:27017"
    thumbor:
        image: apsl/thumbor:6.1.2
        volumes:
            - ./web:/images
            - ./thumbor_cache:/images_cache
            - ./thumbor_resized:/images_resized
        networks:
            new:
                aliases:
                    - thumbor.todevise.com
        ports:
            - "8000:8000"
        environment:
            MAX_AGE: "604800"
            ALLOW_UNSAFE_URL: "True"
            SECURITY_KEY: "ccpXNPgnXHaONlWlzXTEGg458K9HfE"
            LOADER: "thumbor.loaders.file_loader"
            FILE_LOADER_ROOT_PATH: "/images"
            FILE_STORAGE_ROOT_PATH: "/images_cache"
            RESULT_STORAGE_FILE_STORAGE_ROOT_PATH: "/images_resized"
            RESULT_STORAGE_STORES_UNSAFE: "True"
