<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Actions' => '',
    'Alphanumeric' => '',
    'Based on existing size chart' => '',
    'Cancel' => '',
    'Cancel changes' => '',
    'Categories' => '',
    'Confirm' => '',
    'Create new' => '',
    'Create new option' => '',
    'Create new size chart' => '',
    'Create new tag' => '',
    'Description' => '',
    'Description...' => '',
    'Does this tag allow combos?' => '',
    'Duplicated value!' => '',
    'Edit tag' => '',
    'Enabled' => '',
    'Field name (optional)' => '',
    'Free field' => '',
    'Metric unit' => '',
    'Metric units' => '',
    'Name' => '',
    'None' => '',
    'Numeric' => '',
    'Option name...' => '',
    'Optional' => '',
    'Options' => '',
    'Please specify how many options can be combined' => '',
    'Required' => '',
    'Required!' => '',
    'Save changes' => '',
    'Size' => '',
    'Size charts' => '',
    'Size table name' => '',
    'Tag list' => '',
    'Tag name' => '',
    'Tag name...' => '',
    'Value' => '',
    'Value...' => '',
    'Weight' => '',
    'What kind of tag is it?' => '',
    'With options' => '',
    '' => '@@@@',
    'Title' => 'Titulo',
];
