<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add another tag option +' => '',
    'Add size to the chart' => '',
    'Add video +' => '',
    'Apply to all' => '',
    'Apply to same size' => '',
    'Available sizes' => '',
    'Biography' => '',
    'Cancel' => '',
    'Choose size chart' => '',
    'City' => '',
    'Confirm' => '',
    'Connect photo with tags' => '',
    'Create new combination +' => '',
    'Crop image' => '',
    'Currency' => '',
    'Disabled' => '',
    'Editing work' => '',
    'File drop not available' => '',
    'Invalid input' => '',
    'Made to order' => '',
    'Money-back guarantee (days)' => '',
    'No returns' => '',
    'Numbers only' => '',
    'Pre-order' => '',
    'Price' => '',
    'Price & Stock' => '',
    'Prints' => '',
    'Product description' => '',
    'Product name' => '',
    'Publish' => '',
    'Save' => '',
    'Save chart to use with other products' => '',
    'Save progress' => '',
    'Select category/ies' => '',
    'Select country' => '',
    'Select currency' => '',
    'Select language(s)' => '',
    'Select option(s)' => '',
    'Select sizechart' => '',
    'Select weight unit' => '',
    'Set as product\'s main photo' => '',
    'Size' => '',
    'Sizes' => '',
    'Stock' => '',
    'The price & stock table will be available when all required tags have at least 1 combination.' => '',
    'This is a bespoke work' => '',
    'This is in pre-order' => '',
    'This photo hasn\'t been uploaded yet' => '',
    'This work is made-to-order' => '',
    'Upload header photo' => '',
    'Upload profile photo' => '',
    'Uploading...' => '',
    'Video' => '',
    'Warranty (months)' => '',
    'Weight' => '',
    'When the pre-order is over, you will be reminded to update the stock of the product.' => '',
    'When will the pre-order period end?' => '',
    'When will the product be shipped?' => '',
    'Which size system do you use?' => '',
    'Your name' => '',
    'days to manufacturing' => '',
    'or select a previously saved chart' => '',
];
