<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'DEVISER_NEW_ORDER_SUBJECT' => 'TIENES UN NUEVO PEDIDO',
	'DEVISER_NEW_ORDER_HEADER' => 'Tienes un nuevo pedido',
	'DEVISER_NEW_ORDER_HELLO' => 'Hola {{deviser_name}}',
	'DEVISER_NEW_ORDER_TEXT' => '{{client_name}} ha comprado los siguientes productos:',
	'DEVISER_NEW_ORDER_TEXT_2' => 'Por favor, inicia sesión en tu cuenta de Todevise y haznos saber que estás al tanto de la venta (incluso si todavía no estás preparado para enviarlo, necesitamos saber que has visto la notificación).',
	'DEVISER_NEW_ORDER_BUTTON_TEXT' => 'IR A MI CUENTA',

	'DEVISER_NEW_ORDER_REMINDER_24_SUBJECT' => 'RECORDATORIO: TIENES UNA NUEVA VENTA',
	'DEVISER_NEW_ORDER_REMINDER_24_HEADER' => 'RECORDATORIO: TIENES UNA NUEVA VENTA',
	'DEVISER_NEW_ORDER_REMINDER_24_HELLO' => 'Hola {{deviser_name}}',
	'DEVISER_NEW_ORDER_REMINDER_24_TEXT' => '{{client_name}} ha comprado los siguientes productos:',
	'DEVISER_NEW_ORDER_REMINDER_24_TEXT_2' => 'Por favor, haznos saber si has visto esta venta y cubre la información de envío cuando hayas enviado el paquete. Puedes hacerlo desde AJUSTES - MIS PEDIDOS.',
	'DEVISER_NEW_ORDER_REMINDER_24_BUTTON_TEXT' => 'IR A MI CUENTA',

	'DEVISER_NEW_ORDER_REMINDER_48_SUBJECT' => 'RECORDATORIO: UNA DE TUS VENTAS NO HA SIDO ATENDIDA',
	'DEVISER_NEW_ORDER_REMINDER_48_HEADER' => 'RECORDATORIO: UNA DE TUS VENTAS NO HA SIDO ATENDIDA',
	'DEVISER_NEW_ORDER_REMINDER_48_HELLO' => 'Hola {{deviser_name}}',
	'DEVISER_NEW_ORDER_REMINDER_48_TEXT' => '{{client_name}} ha comprado los siguientes productos:',
	'DEVISER_NEW_ORDER_REMINDER_48_TEXT_2' => 'Tienes una venta sin atender. Por favor, inicia sesión en tu cuenta de Todevise, haznos saber si has visto la venta, y cubre la información de envío cuando envíes el paquete.',
	'DEVISER_NEW_ORDER_REMINDER_48_BUTTON_TEXT' => 'IR A MI CUENTA',

	'DEVISER_NO_SHIPPED_24_SUBJECT' => '¿HAS ENVIADO TU PAQUETE?',
	'DEVISER_NO_SHIPPED_24_HEADER' => '¿HAS ENVIADO TU PAQUETE?',
	'DEVISER_NO_SHIPPED_24_HELLO' => 'Hola {{deviser_name}}',
	'DEVISER_NO_SHIPPED_24_TEXT' => '{{client_name}} ha comprado los siguientes productos:',
	'DEVISER_NO_SHIPPED_24_TEXT_2' => 'Por favor, haznos saber si has visto esta venta. ¿Estás preparado para enviar el paquete? Si es así, por favor cubre la información de envío accendiendo a AJUSTES - MIS PEDIDOS, y pulsa en el botón PAQUETE ENVIADO.',
	'DEVISER_NO_SHIPPED_24_BUTTON_TEXT' => 'IR A MI CUENTA',

	'DEVISER_NO_SHIPPED_48_SUBJECT' => 'POR FAVOR CUBRE LA INFORMACIÓN DE ENVÍO PARA EL PEDIDO #{{order_number}}',
	'DEVISER_NO_SHIPPED_48_HEADER' => 'POR FAVOR CUBRE LA INFORMACIÓN DE ENVÍO PARA EL PEDIDO #{{order_number}}',
	'DEVISER_NO_SHIPPED_48_HELLO' => 'Hola {{deviser_name}}',
	'DEVISER_NO_SHIPPED_48_TEXT' => '{{client_name}} ha comprado los siguientes productos:',
	'DEVISER_NO_SHIPPED_48_TEXT_2' => 'Por favor cubre la información de envío para el pedido #(número pedido). El cliente será informado the que el paquete ha sido enviado solo si cubres esta información.',
	'DEVISER_NO_SHIPPED_48_BUTTON_TEXT' => 'IR A MI CUENTA',

	'DEVISER_NO_SHIPPED_72_SUBJECT' => '¡IMPORTANTE! INFORMACIÓN DE ENVÍO DESCONOCIDA PARA EL PEDIDO  #{{order_number}}',
	'DEVISER_NO_SHIPPED_72_HEADER' => '¡IMPORTANTE! INFORMACIÓN DE ENVÍO DESCONOCIDA PARA EL PEDIDO #{{order_number}}',
	'DEVISER_NO_SHIPPED_72_HELLO' => 'Hola {{deviser_name}}',
	'DEVISER_NO_SHIPPED_72_TEXT' => '{{client_name}} ha comprado los siguientes productos:',
	'DEVISER_NO_SHIPPED_72_TEXT_2' => 'En Todevise siempre ponemos a nuestros compradores primero, y necesitamos tenerles actualizados sobre el estado de sus pedidos. La información de envío para el pedido #{{order_number}} no existe. Por favor cúbrela y pulsa en el botón "PAQUETE ENVIADO" tan pronto como sea posible.',
	'DEVISER_NO_SHIPPED_72_BUTTON_TEXT' => 'IR A MI CUENTA',

	'CLIENT_NEW_ORDER_SUBJECT' => 'Enhorabuena, tu compra se ha realizado correctamente',
	'CLIENT_NEW_ORDER_HEADER' => 'Enhorabuena, tu compra se ha realizado correctamente',
	'CLIENT_NEW_ORDER_HELLO' => 'Hola {{client_name}}',
	'CLIENT_NEW_ORDER_TEXT' => 'Has comprado los siguientes productos en Todevise:',
	'CLIENT_NEW_ORDER_TEXT_2' => 'Precio total (sin envío): {order_total}€',
	'CLIENT_NEW_ORDER_TEXT_3' => 'Esto no es una factura. La factura/s para tu pedido será enviada por el deviser/s, y las podrás descargar desde tu cuenta Todevise accediendo a AJUSTES - MIS PEDIDOS.<br />Te enviaremos un email cuando los productos sean enviados.',
	'CLIENT_NEW_ORDER_BUTTON_TEXT' => 'IR A MI CUENTA',

	'CLIENT_NEW_ORDER_SHIPPED_SUBJECT' => 'Tus productos han sido enviados',
	'CLIENT_NEW_ORDER_SHIPPED_HEADER' => 'Tus productos han sido enviados',
	'CLIENT_NEW_ORDER_SHIPPED_HELLO' => 'Hola {{client_name}}',
	'CLIENT_NEW_ORDER_SHIPPED_TEXT' => 'Los siguientes productos de {{deviser_name}} han sido enviados:',
	'CLIENT_NEW_ORDER_SHIPPED_TEXT_2' => '<p>La información de envío es la siguiente:</p><p> - Compañía de transporte: {{company}}</p><p> - Nº de seguimiento: {{tracking_number}}</p><p> - Enlace al seguimiento: {{tracking_link}}</p>',
	'CLIENT_NEW_ORDER_SHIPPED_BUTTON_TEXT' => 'IR A MI CUENTA',

	'TODEVISE_ORDER_72_SUBJECT' => 'Pedido no atendido tras 72 horas!',
	'TODEVISE_ORDER_72_HEADER' => 'Pedido no atendido tras 72 horas!',
	'TODEVISE_ORDER_72_HELLO' => 'Hola Todevise',
	'TODEVISE_ORDER_72_TEXT' => 'El deviser {{deviser_name}} no ha pulsado el botón I’M AWARE para el pedido #{{order_number}}, con los productos:',
	'TODEVISE_ORDER_72_TEXT_2' => '',
	'TODEVISE_ORDER_72_BUTTON_TEXT' => '',

	'TODEVISE_ORDER_96_SUBJECT' => 'Pedido no enviado tras 96 horas!',
	'TODEVISE_ORDER_96_HEADER' => 'Pedido no enviado tras 96 horas!',
	'TODEVISE_ORDER_96_HELLO' => 'Hola Todevise',
	'TODEVISE_ORDER_96_TEXT' => 'El deviser {{deviser_name}} no ha cubierto la información de envío para el pedido #{{order_number}}.',
	'TODEVISE_ORDER_96_TEXT_2' => '',
	'TODEVISE_ORDER_96_BUTTON_TEXT' => '',
];
