<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ERROR_IMPORT_TITLE'            => 'Ha habido errores durante la importación',
    'FILE_NOT_UPLOADED_CORRECTLY'   => 'Archivo no cargado correctamente',
    'FILE_TYPE_NOT_CSV'             => 'El archivo cargado no es un archivo CSV',
    'NO_SOURCE_URL_ALERT'           => 'No has introducido la URL de tu tienda Magento. Las imágenes no serán subidas. ¿Estás seguro de continuar?',
    'IMPORT_WORKS'                  => 'Importar trabajos',
    'IMPORT_WORKS_TITLE'            => 'Importar trabajos',
    'IMPORT_SOURCE'                 => 'Origen de importación',
    'IMPORT_LANGUAGE'               => 'Idioma de importación',
    'CSV_FILE'                      => 'CSV file',
    'UPLOAD_FILE'                   => 'Cargar file',
    'IMPORT_SUBMIT'                 => 'Importar',
    'IMPORT_LANG_ENGLISH'           => 'Inglés',
    'IMPORT_LANG_SPANISH'           => 'Español',
    'SOURCE_SHOP_URL'               => 'URL de la página principal de la tienda',
];
