<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'TITLE' => 'Aviso legal y política de privacidad',
	'TEXT' =>
		'
			<p class="pull-right">Última actualización: septiembre de 2017</p>						
			<p>En cumplimiento del artículo 10 de la Ley 34/2002, de 11 de julio, de Servicios de la Sociedad de la Información y Comercio Electrónico, se exponen los siguientes datos identificativos del prestador del servicio a través del sitio web todevise.com (en adelante, la Plataforma o el Servicio):
			 
			<p><b>Nombre: </b>Tessaractic, SL 
			<p><b>Domicilio: </b>Av. Sant Francesc, 21 3º A 17001 Girona
			<p><b>NIF: </b>B-55136360
			<p><b>Correo electrónico: </b>info@todevise.com
			<p>Registro Mercantil de Girona Tomo 2872 Folio 138 Hoja GI 53739 Inscripción 1</p>
			
			<p>Tessaractic, S.L (en adelante, Todevise) manifiesta su compromiso de cumplir con la legislación vigente en cada momento en materia de protección de datos, concretamente con la Ley Orgánica 15/1999, de 13 de diciembre, de Protección de Datos de Carácter Personal; el Real Decreto 1720/2007, de 21 de diciembre, que aprueba el Reglamento de desarrollo de la Ley Orgánica 15/1999; el Reglamento (UE) 2016/679 del Parlamento Europeo y del Consejo, de 27 de abril de 2016, y demás legislación aplicable. De conformidad con el artículo 5 de la Ley 15/1999, de 13 de diciembre, de Protección de Datos de Carácter Personal, se informa a los Usuarios que los datos de carácter personal que sean facilitados en la Plataforma serán objeto de tratamiento automatizado y pasarán a formar parte de los ficheros titularidad de la Todevise, como responsable del ficheros debidamente inscrito en el Registro General de la Agencia Española de Protección de Datos, para las finalidades propias de gestión de Usuarios registrados en la Plataforma de Todevise.</p>
			
			<br />
			<b>Información básica sobre Protección de Datos</b>
			<div class="table-responsive">
				<table class="table">
					<tr>
						<td>Responsable del tratamiento</td>
						<td>TESSARACTIC, S.L.     NIF: B55136360</td>
					</tr>
					<tr>
						<td>Finalidad del tratamiento
						<td>Gestión y prestación de servicios solicitados</td>
					</tr>
					<tr>
						<td>Legitimación del tratamiento</td>
						<td>Cumplimentación de formularios Plataforma, Registro de usuarios y uso del Servicio.</td>
					</tr>
					<tr>
						<td>Destinatarios de cesiones o transferencias</td>
						<td>No se prevén cesiones de datos a terceras personas</td>
					</tr>
					<tr>
						<td>Derechos</td>
						<td>Acceder, rectificar y cancelar los datos, así como otros derechos, como se explica en la información adicional.</td>
					</tr>
				</table>
			</div>
			<p>Puede consultar información adicional y detallada en nuestra Protección de datos en los apartados siguientes.</p>
			
			<p>De acuerdo con la legislación aplicable, a continuación, se detalla la Política de Privacidad que la Todevise utiliza en el tratamiento de los datos de los Usuarios que se registran en la Plataforma.</p>
			
			<b>¿Quién es el responsable de los Datos que usted nos facilita?</b>
			<p>Toda la información personal que facilite o se recoja a través de todevise.com, será tratada por:</p>
			<div class="table-responsive">
				<table class="table">
					<tr>
						<td colspan="2">Responsable del tratamiento de sus datos</td>
					</tr>
					<tr>
						<td>Responsable</td>
						<td>TESSARACTIC, S.L.     NIF: B55136360</td>
					</tr>        
					<tr>        
						<td>Dirección Postal</td>
						<td>Av. Sant Francesc, 21 3º A 17001 Girona</td>
					</tr>
					<tr>
						<td>Teléfono</td>
						<td>+34 697 408 766</td>
					</tr>
					<tr>
						<td>Correo electrónico</td>
						<td>info@todevise.com</td>
					</tr>
				</table>
			</div>
			 
			<br />
			<b>¿Cuál es la legitimación para el tratamiento de sus datos?</b>
			<p>La base legal para el tratamiento de los datos es el contacto por cualquiera de las vías disponibles en la Plataforma (formularios, e-mail contacto), la ejecución del registro del Usuario en la Plataforma y el posterior uso que el Usuario pueda hacer de la misma.</p>
			 
			<br />
			<b>¿Qué información recopila la Todevise?</b>
			<p>La información que recibimos en la Plataforma por parte de los Usuarios se recopila como exponemos a continuación.</p> 
			<p>a) Información que los Usuarios nos facilitan directamente:</p>
			<p>Todevise recopila y almacena cierta información que el Usuario introduce en la Plataforma o que la facilita de cualquier otro modo:</p>
			<p> - Datos de Registro: la información que el Usuario nos facilita cuando se crea una cuenta en la Plataforma. Esto es, el nombre del Usuario, el correo electrónico, domicilio…etc</p>
			<p> - Información del Perfil del Usuario: la información que el Usuario añade en la Plataforma a efectos de poder utilizar el Servicio. El Usuario puede ver y editar los datos personales de su perfil cuando estime oportuno.</p>
			<p> - Datos de la cuenta del Usuario: la información de los pedidos realizados por parte del Usuario.</p>
			<p> - Información adicional que el Usuario quiere compartir: la información que podría facilitar el Usuario a Todevise con otros fines. Por ejemplo, la dirección de facturación, en caso de solicitar recibir facturas de Todevise.</p>
			
			<p>b) Información que los Usuarios nos facilitan indirectamente:</p>
			<p>Datos derivados del Uso de la Plataforma: Todevise recolecta los datos derivados del Uso de la Plataforma por parte del Usuario cada vez que éste interactúa con la Plataforma.</p>
			<p>Datos del dispositivo: Todevise almacena los datos del dispositivo de conexión que el Usuario utiliza para acceder al Servicio. Estos son: Dirección IP de Internet que utiliza el Usuario para conectarse a Internet con su ordenador o móvil, información de su ordenador o móvil, conexión a Internet, su tipo de navegador, la versión y el sistema operativo, y el tipo de dispositivo, el clickstream completo de localizadores de recursos Uniformes (URL), incluyendo la fecha y la hora, el número de “cookie” del Usuario, el historial de navegación y las preferencias del Usuario.</p> 
			<p>Datos derivados del origen del Usuario: si el Usuario llega a la Plataforma de  Todevise a través de una fuente externa (como sería por ejemplo un enlace de otra página web o de una red social), Todevise recopila los datos de la fuente de la que procede el Usuario.</p>
			<p>Datos derivados de las “cookies”: Todevise utiliza cookies propias y de terceros para facilitar la navegación a sus Usuarios con fines estadísticos.</p>
			<p>Datos derivados de terceros externos: Todevise podría recopilar información o datos de carácter personal de terceros externos únicamente si el Usuario autoriza a esos terceros a compartir la información.</p> 
			
			<br />
			<b>¿Con qué finalidad se recopilan los datos?</b>
			<p>1.- Todevise utiliza los datos que recopila de los Usuarios para prestar el Servicio que solicite el Usuario a través de su cuenta en la Plataforma, según el mecanismo descrito en los “Términos de Uso”.</p>
			<p>2.- Todevise también utiliza la información para investigar y analizar cómo mejorar los servicios que presta a los Usuarios, así como para desarrollar y mejorar las características del servicio que ofrece.</p>
			<p>3.- Todevise también puede utilizar la información de los Usuarios con el propósito de detectar e investigar fraudes, así como otras actividades ilegales y quebrantamientos potenciales de nuestros “Términos de Uso”.</p>
			<p>4.- Internamente, Todevise utiliza la información con fines estadísticos a efectos de analizar el comportamiento y las tendencias de los Usuarios, de comprender cómo los Usuarios utilizan la Plataforma, y de gestionar y mejorar los servicios ofrecidos, incluyendo la posibilidad de añadir nuevos distintivos.</p>
			<p>5.- Asimismo, Todevise podrá utilizar los datos personales que el Usuario le facilita para realizar comunicaciones vía correo electrónico y/o enviar SMS al Usuario acerca de la operativa del servicio. Todevise enviará mensajes al Usuario con información relativa al estado del pedido solicitado, y una vez éste haya terminado, Todevise enviará un resumen/recibo del pedido y del precio del mismo al correo electrónico del Usuario. Al registrarse en la Plataforma se entenderá que el Usuario acepta la presente Política de Privacidad y que, por lo tanto, autoriza a la Todevise para realizar ambas comunicaciones.</p>
			<p>6.- Por otro lado, Todevise, con el consentimiento del Usuario, podrá enviar al correo electrónico de los Usuarios mensajes promocionales y/o ofertas relativas al Servicio. Si el Usuario desea no recibir la citada información y/o comunicaciones comerciales, los Usuarios podrán optar en cualquier momento a la opción de “Cancelar la suscripción” en el propio correo electrónico, y consecuentemente, Todevise cesará inmediatamente en el envío de la citada información.</p>
			<p>7.- Si el Usuario conecta su cuenta a otra red social o a la Web de un tercero, Todevise podría utilizar la información cedida a esa red social o tercero, siempre que dicha información se haya puesto a disposición de Todevise con el consentimiento del Usuario.</p>
			
			<br />
			<b>¿Por cuánto tiempo conservaremos sus datos?</b>
			<p>Los datos personales proporcionados se conservarán mientras no se solicite su supresión por el interesado durante un plazo de 24 meses desde la última interacción.</p>
			
			<br />
			<b>¿Comparte Todevise la información que recopila?</b>
			<p>Los datos de carácter personal que Todevise recopile serán exclusivamente utilizados para la consecución del objeto definido en los “Términos de Uso”. Todevise no cederá sus datos a otras compañías excepto que cuente con el consentimiento previo y expreso del Usuario. En todo momento, el único destinatario de la información contenida en los datos de carácter personal del Usuario será la Todevise, a excepción de que el Usuario, voluntariamente, y así lo manifieste de forma expresa, desee, la divulgación de dicha información personal a través de los medios de que dispone la Plataforma, en orden a poderle prestarle determinados servicios relacionados con el Servicio.</p>
			
			<br />
			<b>¿Qué derechos tienen los Usuarios?</b>
			<p>Todevise da al Usuario acceso a una gran cantidad de información sobre su cuenta y sus operaciones en la Plataforma para que pueda ver, y en ciertos casos, actualizar dicha información.</p>
			<p>Todo Usuario podrá acceder al perfil del Usuario y completarlo y/o editarlo según estime conveniente. La información y datos facilitados por el Usuario estarán en todo momento disponibles en la cuenta del Usuario y podrán ser modificados por el Usuario a través de la opción editar perfil.</p>
			<p>El Usuario podrá ejercer sus derechos de acceso, rectificación, cancelación y oposición, teniendo en cuenta que el ejercicio de los mismos es personalísimo, por lo que será necesario que el afectado acredite su identidad. El ejercicio de estos derechos deberá realizarse por escrito firmado por el titular de los datos, con indicación de su domicilio, adjuntando copia de su Documento Nacional de Identidad u otro documento acreditativo, dirigiéndose al correo electrónico de contacto de Todevise.</p>
			<p>Como se ha indicado anteriormente, si el Usuario desea dejar de recibir correos electrónicos de Todevise podrá ajustar sus suscripciones en la bandeja de correo electrónico y presionar el botón “Cancelar la Suscripción”.</p>
			
			<br />
			<b>¿Cómo protegemos los datos de los Usuarios?</b>
			<p>Todevise ha adoptado las medidas necesarias para mantener el nivel de seguridad requerido, según la naturaleza de los datos personales tratados y las circunstancias del tratamiento, con el objeto de evitar, en la medida de lo posible y siempre según el estado de la técnica, su alteración, pérdida, tratamiento o acceso no autorizado. Como se ha mencionado anteriormente, los datos personales facilitados no serán cedidos a terceros sin autorización previa por parte del titular de los mismos.</p>
			<p>Asimismo Todevise informa a los Usuarios que tienen derecho a ejercitar ante la Agencia Española de Protección de Datos, como Autoridad de Control competente en materia de Protección de Datos, el ejercicio de la tutela efectiva de los derechos aquí reconocidos.</p>

	',
];