<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'ABOUT_PERSON_NAME' => 'Acerca de {person_name}',
	'ABOUT_US' => 'Sobre nosotros',
	'ALL_CATEGORIES' => 'Todas las categorías',
	'ALMOST_DONE_PERSON_NAME' => '¡Casi ha terminado! {person_name}',
	'BECOME_A_DEVISER' => 'Convertirse en deviser',
	'BILLINGS_AND_PAYMENTS' => 'Facturas y Pagos',
	'BOXES_BY_PERSON_NAME' => 'Cajas de {person_name}',
	'BOX_NAME_BY_PERSON_NAME' => '{box_name} de {person_name}',
	'CANCEL' => 'Cancelar',
	'CART' => 'Carrito',
	'CATEGORY_WORKS_BY_PERSON_NAME' => 'Trabajos de {category_name} de {person_name}',
	'CHECKOUT' => 'Checkout',
	'COMPLETE_PROFILE_PERSON_NAME' => '¡Completa tu perfil! {person_name}',
	'CONFIRM' => 'Confirmar',
	'CONNECT_WITH_DIFFERENT_STRIPE_ACCOUNT' => 'Conéctate con una cuenta de Stripe diferente',
	'CONNECT_WITH_STRIPE' => 'Conéctate con Stripe',
	'CONTACT_TITLE' => 'Contacta con nosotros',
	'CONTACT_HEADER' => 'Contacta con nosotros',
	'CONTACT_NAME' => 'Nombre',
	'CONTACT_EMAIL' => 'Email',
	'CONTACT_MESSAGE_PLACEHOLDER' => 'Escribe un mensaje',
	'CONTACT_WHATSAPP_HEADER' => 'Contacta por Whatsapp',
	'CONTACT_WHATSAPP_TEXT' => 'Simplemente añade este número a tu lista de contacto e inicia una conversación con nosotros',
	'CONTACT_WHATSAPP_NUMBER' => '+34 645 234 234',
	'CONTACT_WHATSAPP_INFO' => 'Debido a las diferencias horarias, la respuesta de nuestros agentes puede demorarse hasta 24 horas',
	'CONTACT_FACEBOOK_HEADER' => 'Contacta por Facebook',
	'CONTACT_FACEBOOK_TEXT_1' => 'Puedes escribirnos vía Facebook. Nuestro equipo de redes sociales te responderá en menos de 24 horas.',
	'CONTACT_FACEBOOK_TEXT_2' => 'Pulsa el siguiente botón para ir a nuestro perfil',
	'CONTACT_FACEBOOK_BUTTON' => 'Contactar vía Facebook',
	'CREATE_AN_INFLUENCER_ACCOUNT' => 'Crea una cuenta de influencer',
	'CREATE_A_DEVISER_ACCOUNT' => 'Crea una cuenta de deviser',
	'CREATE_NEW_WORK_BY_PERSON_NAME' => 'Crear nuevo trabajo de {person_name}',
	'DAYS' => 'Días',
	'DISCOVER_DEVISERS' => 'Descubrir devisers',
	'DISCOVER_INFLUENCERS' => 'Descubrir influencers',
	'EDIT_ABOUT_PERSON_NAME' => 'Editar {person_name}',
	'EDIT_PERSON_NAME_FAQS' => 'Editar faqs de {person_name}',
	'EDIT_PRESS_BY_PERSON_NAME' => 'Editar prensa de {person_name}',
	'EDIT_PRODUCT_BY_PERSON_NAME' => 'Editar {product_name} de {person_name}',
	'EDIT_STORY_BY_PERSON_NAME' => 'Editar la historia {story_title} by {person_name}',
	'EDIT_VIDEOS_BY_PERSON_NAME' => 'Editar videos de {person_name}',
	'EDIT_WORKS_BY_PERSON_NAME' => 'Editar trabajos de {person_name}',
	'EXPLORE_BOXES' => 'Explora las cajas',
	'INCORRECT_USERNAME_OR_PASSWORD' => 'Nombre de usuario o contraseña incorrectos',
	'INDEX_TITLE' => 'Todevise',
	'LANGUAGE' => 'Idioma',
	'LOVED_BY_PERSON_NAME' => 'Loved de {person_name}',
	'MONTHS' => 'Meses',
	'NEW_STORY_BY_PERSON_NAME' => 'Nueva historia de {person_name}',
	'NONE' => 'Ninguno',
	'ORDERS' => 'Órdenes',
	'ORDER_ID_COMPLETED' => 'Orden {order_id} completada',
	'ORDER_EMAIL_ORDER_NUMBER' => 'Pedido nº {order_id}',
	'ORDER_EMAIL_TITLE' => 'CONFIRMACIÓN DE COMPRA',
	'ORDER_EMAIL_HELLO' => 'Hola {person_name},',
	'ORDER_EMAIL_MAIN_TEXT' => 'Te informamos que tu compra ha sido realizada&nbsp;con éxito y se encuentra&nbsp;en proceso de envío. Para devoluciones o modificaciones visita tu perfil en <a href="http://beta.todevise.com" target="_blank">todevise.com</a>',
	'ORDER_EMAIL_PRICE' => 'Precio',
	'ORDER_EMAIL_SUBTITLE' => 'Información de compra',
	'ORDER_EMAIL_TOTAL_AMOUNT' => 'IMPORTE TOTAL DE LA COMPRA: <strong>{amount}</strong>',
	'ORDER_EMAIL_FOOTER' => '<em>To learn more about Todevise, click on this link</em>&nbsp;<a href="http://www.todevise.com/about-us">http://www.todevise.com/about-us</a><br><em>Copyright @ 2017 Todevise, All rights reserved.</em><br>',
	'PAYMENTS_MADE_TROUGH_STRIPE' => 'Todos los pagos de Todevise se realizan a través de Stripe, una plataforma de procesamiento de pagos. Usamos Stripe porque es muy seguro, rápido y fácil de usar. La comisión de Stripe es de 1,40% + 0,25€ de cada transacción. El dinero será transferido a su cuenta de Stripe inmediatamente después de cada compra. <br /><br/>Para empezar a vender en Todevise, debes abrir una cuenta de Stripe (es 100% gratis) y conectarla a tu perfil Todevise. Para ello, pulse el botón de abajo. Cuando termine de crear su cuenta de Stripe, será redirigido a esta página.',
	'PERSON_NAME_FAQS' => 'Faqs',
	'PRESS_BY_PERSON_NAME' => 'Prensa de {person_name}',
	'PRODUCT_BY_PERSON_NAME' => '{product_name} de {person_name}',
	'PROFILE_AND_STRIPE_LINKED_INFO' => 'Tu perfil Todevise y tu cuenta de Stripe están ahora enlazados. ¿Desea conectar su perfil a una cuenta Stripe diferente? Presione el botón de abajo.',
	'SELECT_CATEGORY' => 'Selecciona categoría',
	'SELECT_COUNTRY' => 'Selecciona el país',
	'SELECT_METRIC_UNIT' => 'Selecciona la unidad métrica',
	'SETTINGS' => 'Ajustes',
	'SHIPPING_SETTINGS' => 'Preferencias de envío',
	'SIGNUP' => 'Regístrate',
	'SOCIAL_FEED_BY_PERSON_NAME' => 'Social feed by {person_name}',
	'STORIES' => 'Historias',
	'STORY_BY_PERSON_NAME' => 'Historias',
	'VIDEOS_BY_PERSON_NAME' => 'Videos de {person_name}',
	'WEEKS' => 'Semanas',
	'WORKS' => 'Trabajos',
	'WORKS_BY_PERSON_NAME' => 'Trabajos de {person_name}',
	'WORKS_SEARCH_PARAM' => 'Trabajos - {search_param}',
];
