<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ABOUT_PERSON_NAME' => '',
    'ABOUT_US' => '',
    'ALL_CATEGORIES' => '',
    'ALMOST_DONE_PERSON_NAME' => '',
    'BECOME_A_DEVISER' => '',
    'BILLINGS_AND_PAYMENTS' => '',
    'BOXES_BY_PERSON_NAME' => '',
    'BOX_NAME_BY_PERSON_NAME' => '',
    'CANCEL' => '',
    'CART' => '',
    'CATEGORY_WORKS_BY_PERSON_NAME' => '',
    'CHECKOUT' => '',
    'COMPLETE_PROFILE_PERSON_NAME' => '',
    'CONFIRM' => '',
    'CONNECT_WITH_DIFFERENT_STRIPE_ACCOUNT' => '',
    'CONNECT_WITH_STRIPE' => '',
    'CREATE_AN_INFLUENCER_ACCOUNT' => '',
    'CREATE_A_DEVISER_ACCOUNT' => '',
    'CREATE_NEW_WORK_BY_PERSON_NAME' => '',
    'CROP_IMAGE' => '',
    'DAYS' => '',
    'DISCOVER_DEVISERS' => '',
    'DISCOVER_INFLUENCERS' => '',
    'EDIT_ABOUT_PERSON_NAME' => '',
    'EDIT_PERSON_NAME_FAQS' => '',
    'EDIT_PRESS_BY_PERSON_NAME' => '',
    'EDIT_PRODUCT_BY_PERSON_NAME' => '',
    'EDIT_STORY_BY_PERSON_NAME' => '',
    'EDIT_VIDEOS_BY_PERSON_NAME' => '',
    'EDIT_WORKS_BY_PERSON_NAME' => '',
    'EXPLORE_BOXES' => '',
    'INCORRECT_USERNAME_OR_PASSWORD' => '',
    'INDEX_TITLE' => '',
    'LANGUAGE' => '',
    'LOVED_BY_PERSON_NAME' => '',
    'MONTHS' => '',
    'NEW_STORY_BY_PERSON_NAME' => '',
    'NONE' => '',
    'ORDERS' => '',
    'ORDER_ID_COMPLETED' => '',
    'PAYMENTS_MADE_TROUGH_STRIPE' => '',
    'PERSON_NAME_FAQS' => '',
    'PRESS_BY_PERSON_NAME' => '',
    'PRODUCT_BY_PERSON_NAME' => '',
    'PROFILE_AND_STRIPE_LINKED_INFO' => '',
    'SELECT_CATEGORY' => '',
    'SELECT_COUNTRY' => '',
    'SELECT_METRIC_UNIT' => '',
    'SETTINGS' => '',
    'SHIPPING_SETTINGS' => '',
    'SIGNUP' => '',
    'STORIES' => '',
    'STORY_BY_PERSON_NAME' => '',
    'VIDEOS_BY_PERSON_NAME' => '',
    'WEEKS' => '',
    'WORKS' => '',
    'WORKS_BY_PERSON_NAME' => '',
    'WORKS_SEARCH_PARAM' => '',
];
