<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'TITLE' => 'Devoluciones & garantías',

	'BLOCK_1_TITLE' => 'Lee las políticas de envíos y devoluciones de cada deviser antes de comprar',
	'BLOCK_1_TEXT_1' => 'Puedes encontrar esta información en la ficha de producto, en el apartado de ENVÍO & CONDICIONES.',
	'BLOCK_1_TEXT_2' => 'Los devisers se encargan de controlar sus tiendas y de enviar los productos, y tienen la libertad de definir sus condiciones de envíos, garantías y devoluciones.',

	'BLOCK_2_TITLE' => 'Devolver un producto',
	'BLOCK_2_TEXT_1' => 'Antes de iniciar el proceso de devolución, te aconsejamos que hables con el deviser a través de nuestro CHAT. Para acceder al chat con un deviser, tienes que entrar en su perfil y clicar el botón ENVIAR UN MENSAJE.',
	'BLOCK_2_TEXT_2' => 'Antes de devolver el producto, pídele al deviser la siguiente información:',
	'BLOCK_2_TEXT_3' => '<ul><li>/ la confirmación de que aceptan la devolución</li><li>/ la dirección para la devolución</li><li>/ un acuerdo sobre quién cubre los gastos de envío</li></ul>',

	'BLOCK_3_TITLE' => '¿No has podido devolver tu producto?',
	'BLOCK_3_TEXT_1' => 'Si no has podido llegar a un acuerdo con el deviser, o has encontrado cualquier tipo de dificultad en el proceso de devolución, contacta con nuestro departamento de atención al cliente <a href="{contact_link}"><strong>aquí</strong></a>.',

];
