<?php
/**
 * This file is generated by the "yii asset" command.
 * DO NOT MODIFY THIS FILE DIRECTLY.
 * @version 2017-09-12 09:55:52
 */
return [
    'all' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/assets',
        'baseUrl' => '@web/assets',
        'js' => [
            'all-4af0a08955a96d3ac343ce4583e5c101.js',
        ],
        'css' => [
            'all-f3413f19be9d499f194e62f828b8d93a.css',
        ],
        'sourcePath' => null,
        'depends' => [],
    ],
    'yii\\web\\JqueryAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'all',
        ],
    ],
    'yii\\web\\YiiAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'all',
        ],
    ],
    'app\\assets\\libs\\bootstrapAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'all',
        ],
    ],
    'app\\assets\\libs\\angularAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'all',
        ],
    ],
    'app\\assets\\libs\\angularAnimateAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\libs\\angularAsset',
            'all',
        ],
    ],
    'app\\assets\\libs\\angularBootstrapAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\libs\\angularAsset',
            'app\\assets\\libs\\angularAnimateAsset',
            'all',
        ],
    ],
    'app\\assets\\libs\\angularTranslateAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\libs\\angularAsset',
            'all',
        ],
    ],
    'app\\assets\\libs\\angularTranslateLoaderPartialAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\libs\\angularAsset',
            'app\\assets\\libs\\angularTranslateAsset',
            'all',
        ],
    ],
    'app\\assets\\AppAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'app\\assets\\libs\\bootstrapAsset',
            'app\\assets\\libs\\angularAsset',
            'app\\assets\\libs\\angularBootstrapAsset',
            'app\\assets\\libs\\angularTranslateLoaderPartialAsset',
            'all',
        ],
    ],
    'app\\assets\\libs\\angularResourceAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\libs\\angularAsset',
            'all',
        ],
    ],
    'app\\assets\\libs\\ngFileUploadAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\libs\\angularAsset',
            'all',
        ],
    ],
    'app\\assets\\libs\\angularMessagesAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\libs\\angularAsset',
            'all',
        ],
    ],
    'app\\assets\\libs\\uiCropperAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\libs\\angularAsset',
            'all',
        ],
    ],
    'app\\assets\\libs\\angularLocalStorageAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\libs\\angularAsset',
            'all',
        ],
    ],
    'app\\assets\\libs\\ngInfiniteScrollAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\libs\\angularAsset',
            'all',
        ],
    ],
    'app\\assets\\libs\\utilAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\libs\\angularMessagesAsset',
            'app\\assets\\libs\\uiCropperAsset',
            'app\\assets\\libs\\angularLocalStorageAsset',
            'app\\assets\\libs\\angularBootstrapAsset',
            'app\\assets\\libs\\ngInfiniteScrollAsset',
            'all',
        ],
    ],
    'app\\assets\\api\\ApiAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\libs\\angularAsset',
            'app\\assets\\libs\\angularResourceAsset',
            'app\\assets\\libs\\ngFileUploadAsset',
            'app\\assets\\libs\\utilAsset',
            'all',
        ],
    ],
    'app\\assets\\desktop\\GlobalAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\AppAsset',
            'app\\assets\\api\\ApiAsset',
            'app\\assets\\libs\\utilAsset',
            'all',
        ],
    ],
];