<?php
/**
 * This file is generated by the "yii asset" command.
 * DO NOT MODIFY THIS FILE DIRECTLY.
 * @version 2017-09-18 22:22:41
 */
return [
    'all' => [
        'class' => 'yii\\web\\AssetBundle',
        'basePath' => '@webroot/assets',
        'baseUrl' => '@web/assets',
        'js' => [
            'all.js',
        ],
        'css' => [
            'all.css',
        ],
        'sourcePath' => null,
        'depends' => [],
    ],
    'yii\\web\\JqueryAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'all',
        ],
    ],
    'yii\\web\\YiiAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'all',
        ],
    ],
    'app\\assets\\libs\\bootstrapAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'all',
        ],
    ],
    'app\\assets\\libs\\angularAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'all',
        ],
    ],
    'app\\assets\\libs\\angularAnimateAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\libs\\angularAsset',
            'all',
        ],
    ],
    'app\\assets\\libs\\angularBootstrapAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\libs\\angularAsset',
            'app\\assets\\libs\\angularAnimateAsset',
            'all',
        ],
    ],
    'app\\assets\\libs\\angularTranslateAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\libs\\angularAsset',
            'all',
        ],
    ],
    'app\\assets\\libs\\angularTranslateLoaderPartialAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\libs\\angularAsset',
            'app\\assets\\libs\\angularTranslateAsset',
            'all',
        ],
    ],
    'app\\assets\\AppAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\YiiAsset',
            'app\\assets\\libs\\bootstrapAsset',
            'app\\assets\\libs\\angularAsset',
            'app\\assets\\libs\\angularBootstrapAsset',
            'app\\assets\\libs\\angularTranslateLoaderPartialAsset',
            'all',
        ],
    ],
    'app\\assets\\libs\\angularResourceAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\libs\\angularAsset',
            'all',
        ],
    ],
    'app\\assets\\libs\\ngFileUploadAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\libs\\angularAsset',
            'all',
        ],
    ],
    'app\\assets\\libs\\angularMessagesAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\libs\\angularAsset',
            'all',
        ],
    ],
    'app\\assets\\libs\\uiCropperAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\libs\\angularAsset',
            'all',
        ],
    ],
    'app\\assets\\libs\\angularLocalStorageAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\libs\\angularAsset',
            'all',
        ],
    ],
    'app\\assets\\libs\\ngInfiniteScrollAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\libs\\angularAsset',
            'all',
        ],
    ],
    'app\\assets\\libs\\utilAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\libs\\angularMessagesAsset',
            'app\\assets\\libs\\uiCropperAsset',
            'app\\assets\\libs\\angularLocalStorageAsset',
            'app\\assets\\libs\\angularBootstrapAsset',
            'app\\assets\\libs\\ngInfiniteScrollAsset',
            'all',
        ],
    ],
    'app\\assets\\api\\ApiAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\libs\\angularAsset',
            'app\\assets\\libs\\angularResourceAsset',
            'app\\assets\\libs\\ngFileUploadAsset',
            'app\\assets\\libs\\utilAsset',
            'all',
        ],
    ],
    'app\\components\\assets\\PublicHeader2Asset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\api\\ApiAsset',
            'app\\assets\\libs\\utilAsset',
            'all',
        ],
    ],
    'app\\assets\\desktop\\box\\IndexAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'all',
        ],
    ],
    'app\\assets\\libs\\angularToastrAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\libs\\angularAnimateAsset',
            'all',
        ],
    ],
    'app\\assets\\libs\\nyaBootstrapSelectAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\libs\\angularAsset',
            'all',
        ],
    ],
    'app\\assets\\libs\\textAngularAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\libs\\angularAsset',
            'all',
        ],
    ],
    'app\\assets\\libs\\angularDragAndDropAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\libs\\angularAsset',
            'all',
        ],
    ],
    'app\\assets\\libs\\ngYoutubeEmbedAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\libs\\angularAsset',
            'all',
        ],
    ],
    'app\\assets\\libs\\angularMasonryAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\libs\\angularAsset',
            'all',
        ],
    ],
    'app\\assets\\libs\\ngTagsInputAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\libs\\angularAsset',
            'all',
        ],
    ],
    'app\\assets\\libs\\jqueryUiAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'yii\\web\\JqueryAsset',
            'all',
        ],
    ],
    'app\\assets\\libs\\angularUiSortableAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\libs\\angularAsset',
            'app\\assets\\libs\\jqueryUiAsset',
            'all',
        ],
    ],
    'app\\assets\\desktop\\deviser\\IndexAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\api\\ApiAsset',
            'app\\assets\\libs\\utilAsset',
            'app\\assets\\libs\\nyaBootstrapSelectAsset',
            'app\\assets\\libs\\textAngularAsset',
            'app\\assets\\libs\\ngFileUploadAsset',
            'app\\assets\\libs\\angularDragAndDropAsset',
            'app\\assets\\libs\\ngYoutubeEmbedAsset',
            'app\\assets\\libs\\uiCropperAsset',
            'app\\assets\\libs\\angularMasonryAsset',
            'app\\assets\\libs\\angularLocalStorageAsset',
            'app\\assets\\libs\\ngTagsInputAsset',
            'app\\assets\\libs\\angularUiSortableAsset',
            'all',
        ],
    ],
    'app\\assets\\libs\\momentAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'all',
        ],
    ],
    'app\\assets\\libs\\angularBootstrapDatetimePickerAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\libs\\momentAsset',
            'app\\assets\\libs\\angularAsset',
            'all',
        ],
    ],
    'app\\assets\\libs\\angularXEditableAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\libs\\angularAsset',
            'all',
        ],
    ],
    'app\\assets\\libs\\macyAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'all',
        ],
    ],
    'app\\assets\\desktop\\product\\IndexAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\api\\ApiAsset',
            'app\\assets\\libs\\utilAsset',
            'app\\assets\\libs\\angularBootstrapAsset',
            'app\\assets\\libs\\nyaBootstrapSelectAsset',
            'app\\assets\\libs\\textAngularAsset',
            'app\\assets\\libs\\ngFileUploadAsset',
            'app\\assets\\libs\\angularDragAndDropAsset',
            'app\\assets\\libs\\uiCropperAsset',
            'app\\assets\\libs\\ngTagsInputAsset',
            'app\\assets\\libs\\angularLocalStorageAsset',
            'app\\assets\\libs\\angularBootstrapDatetimePickerAsset',
            'app\\assets\\libs\\angularXEditableAsset',
            'app\\assets\\libs\\macyAsset',
            'app\\assets\\libs\\angularUiSortableAsset',
            'all',
        ],
    ],
    'app\\assets\\desktop\\discover\\IndexAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\api\\ApiAsset',
            'app\\assets\\libs\\utilAsset',
            'app\\assets\\libs\\nyaBootstrapSelectAsset',
            'app\\assets\\libs\\textAngularAsset',
            'app\\assets\\libs\\ngFileUploadAsset',
            'app\\assets\\libs\\angularDragAndDropAsset',
            'app\\assets\\libs\\ngYoutubeEmbedAsset',
            'app\\assets\\libs\\uiCropperAsset',
            'app\\assets\\libs\\angularMasonryAsset',
            'app\\assets\\libs\\angularLocalStorageAsset',
            'app\\assets\\libs\\ngTagsInputAsset',
            'app\\assets\\libs\\angularUiSortableAsset',
            'all',
        ],
    ],
    'app\\assets\\desktop\\settings\\IndexAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\api\\ApiAsset',
            'app\\assets\\libs\\utilAsset',
            'app\\components\\assets\\PublicHeader2Asset',
            'app\\assets\\libs\\textAngularAsset',
            'app\\assets\\libs\\nyaBootstrapSelectAsset',
            'all',
        ],
    ],
    'app\\assets\\libs\\angularLocaleAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\libs\\angularAsset',
            'all',
        ],
    ],
    'app\\assets\\desktop\\cart\\IndexAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\api\\ApiAsset',
            'app\\assets\\libs\\utilAsset',
            'app\\assets\\libs\\angularBootstrapAsset',
            'app\\assets\\libs\\nyaBootstrapSelectAsset',
            'app\\assets\\libs\\textAngularAsset',
            'app\\assets\\libs\\ngFileUploadAsset',
            'app\\assets\\libs\\angularDragAndDropAsset',
            'app\\assets\\libs\\uiCropperAsset',
            'app\\assets\\libs\\ngTagsInputAsset',
            'app\\assets\\libs\\angularLocalStorageAsset',
            'app\\assets\\libs\\angularBootstrapDatetimePickerAsset',
            'app\\assets\\libs\\angularXEditableAsset',
            'app\\assets\\libs\\macyAsset',
            'app\\assets\\libs\\angularUiSortableAsset',
            'app\\assets\\libs\\angularLocaleAsset',
            'all',
        ],
    ],
    'app\\assets\\desktop\\GlobalAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\AppAsset',
            'app\\components\\assets\\PublicHeader2Asset',
            'app\\assets\\api\\ApiAsset',
            'app\\assets\\libs\\utilAsset',
            'app\\assets\\desktop\\box\\IndexAsset',
            'app\\assets\\libs\\angularToastrAsset',
            'app\\assets\\desktop\\deviser\\IndexAsset',
            'app\\assets\\desktop\\product\\IndexAsset',
            'app\\assets\\desktop\\discover\\IndexAsset',
            'app\\assets\\desktop\\settings\\IndexAsset',
            'app\\assets\\desktop\\cart\\IndexAsset',
            'all',
        ],
    ],
    'app\\assets\\desktop\\pub\\PublicCommonAsset' => [
        'sourcePath' => null,
        'js' => [],
        'css' => [],
        'depends' => [
            'app\\assets\\desktop\\GlobalAsset',
            'all',
        ],
    ],
];