<?php
namespace app\modules\api\pub\v1\forms;

use app\models\Person;
use Yii;
use app\helpers\Utils;
use yii\base\Model;

class BecomeDeviserForm extends Model {

	/**
	 * @var string
	 */
	public $email;

	/**
	 * @var string
	 */
	public $representative_name;

	/**
	 * @var string
	 */
	public $brand_name;

	/**
	 * @var string
	 */
	public $phone_number;

	/**
	 * @var string
	 */
	public $creations_description;

	/**
	 * @var array
	 */
	public $urls_portfolio;

	/**
	 * @var array
	 */
	public $urls_video;
	
	/**
	 * @var string
	 */
	public $observations;

	public function init()
	{
		parent::init(); // TODO: Change the autogenerated stub
		$this->urls_portfolio = [];
		$this->urls_video = [];

	}

	public function rules()
	{
		return [
			[['email', 'representative_name', 'creations_description'], 'required'],
			[['email'], 'email'],
			[['urls_portfolio', 'urls_video'], 'each', 'rule' => ['url']],
			[['brand_name', 'phone_number', 'observations'], 'safe'],
		];
	}

}
