<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'TITLE' => 'Política de cookies',
	'TEXT' =>
	'
		<p>Tessaractic, SL (en adelante, Todevise) utiliza cookies en el sitio web todevise.com (en
		adelante, el sitio web) para ayudar a mejorar el servicio del usuario del sitio web (en adelante,
		el Usuario) midiendo el uso y el rendimiento del sitio web así como para optimizarlo y
		personalizarlo.</p>
		
		<p>Las Cookies son ficheros enviados a un navegador por medio de un servidor web para registrar
		las actividades del Usuario en una web determinada. La primera finalidad de las Cookies es la
		de facilitar al Usuario un acceso más rápido a los servicios seleccionados. Además, las Cookies
		personalizan los servicios que ofrece el sitio web, facilitando y ofreciendo a cada Usuario
		información que es de su interés o que puede ser de su interés, en atención al uso que realiza
		de los servicios del sitio web.</p>
		
		<p>Los Usuarios registrados en el sitio web podrán beneficiarse de unos servicios más
		personalizados y orientados a su perfil, gracias a la combinación de los datos almacenados en
		las cookies con los datos personales utilizados en el momento de su registro. Dichos Usuarios
		autorizan expresamente el uso de esta información con la finalidad indicada, sin perjuicio de
		su derecho a rechazar o deshabilitar el uso de cookies.</p>
		
		<p>Asimismo, el sitio web podrá saber todos los servicios solicitados por los Usuarios, de forma
		que podrán facilitar u ofrecer información adecuada a los gustos y preferencias de cada
		Usuario.</p>
		
		<p>Es posible que el sitio web contenga enlaces a otros sitios webs, en este sentido Todevise no
		controla las cookies utilizadas por estos sitios webs externos. Para más información sobre las
		cookies de los sitios webs ajenos, aconsejamos revisar sus propias políticas de cookies.</p>
		
		<p>La legislación vigente nos obliga a solicitar la conformidad del Usuario para poder gestionar las
		cookies. En caso que el Usuario decida no autorizar su uso, Todevise no almacenaría ninguna
		cookie y tan sólo se usarían las cookies técnicas dado que sin ellas no es posible navegar por el
		sitio web. En caso de seguir navegando por el sitio web y no denegar la autorización, dicha
		actividad implicará la aceptación de su uso.</p>
		
		<p>Las cookies utilizadas en la web son las siguientes:</p>
		
		<div class="table-responsive">
			<table class="table"">
				<tr>
					<th>Cookie</th>
					<th>Descripción</th>
					<th>Duración</th>
					<th>Tipo</th>
				</tr>
				<tr>
					<td>lang</td>
					<td>Preferencia de idioma: Se utiliza para recordar qué idioma escogió el visitante en su sesión.</td>
					<td>1 año</td>
					<td>Propias</td>
				</tr>
				<tr>
					<td>.Asp.Net.ApplicationCookie</td>
					<td>Información de usuario autenticado, cuando el usuario desea que el navegador recuerde su usuario.</td>
					<td>2 semanas</td>
					<td>Propias</td>
				</tr>
				<tr>
					<td>__utma</td>
					<td>Identificación de visitantes únicos: Utilizada para registrar visitantes únicos con fines estadísticos y analíticos.</td>
					<td>2 años</td>
					<td>Google (Analytic)</td>
				</tr>
				<tr>
					<td>__utmb</td>
					<td>Determinación de la sesión del visitante: Google Analytics utiliza dos cookies para establecer una sesión. Si falta alguna de estas dos cookies, otra actividad inicia el comienzo de una nueva sesión.</td>
					<td>30 minutos</td>
					<td>Google (Analytic)</td>
				</tr>
				<tr>
					<td>__utmc</td>
					<td>Determinación de la sesión del visitante: Google Analytics utiliza dos cookies para establecer una sesión. Si falta alguna de estas dos cookies, otra actividad inicia el comienzo de una nueva sesión.</td>
					<td>Sesión</td>
					<td>Google (Analytic)</td>
				</tr>
				<tr>
					<td>__utmz</td>
					<td>Registro de fuentes de tráfico y navegación: Utilizado para registrar cómo llegó a nuestro sitio Web (por una búsqueda de Google, un aviso, etc.) y los recorridos que sigue mientras navega nuestro sitio. Utilizamos esta información para mejorar la experiencia del usuario en futuras actualizaciones.</td>
					<td>6 meses</td>
					<td>Google (Analytic)</td>
				</tr>
			</table>
		</div>
		
		<p>El Usuario puede restringir, bloquear o borrar las cookies del sitio web de Todevise utilizando
		su navegador. En cada navegador la operativa es diferente, a continuación se facilitan los
		enlaces a los principales navegadores sobre cómo realizar dichas modificaciones:</p>
		<ul>
			<li><a target="_blank" href="https://support.microsoft.com/es-es/help/17442/windows-internet-explorer-delete-manage-cookies">Internet Explorer</a></li>
			<li><a target="_blank" href="https://support.mozilla.org/es/kb/habilitar-y-deshabilitar-cookies-sitios-web-rastrear-preferencias?redirectlocale=es&redirectslug=habilitar-y-deshabilitar-cookies-que-los-sitios-we">Firefox</a></li>
			<li><a target="_blank" href="https://support.google.com/chrome/answer/95647?hl=es">Chrome</a></li>
			<li><a target="_blank" href="https://www.apple.com/legal/privacy/es/cookies/">Safari</a></li>
		</ul>
		
		<p>En caso de realizar modificaciones en la configuración de las cookies, Todevise informa de que
		no asegura el correcto funcionamiento de las distintas funcionalidades del sitio web.</p>
		
		<p>Todevise puede modificar la presente Política de Cookies en función de las exigencias
		legislativas, reglamentarias, o con la finalidad de adaptar dicha Política a las instrucciones
		dictadas por la Agencia Española de Protección de Datos, por ello se aconseja a los Usuarios
		del sitio web que la visiten periódicamente.</p>
		
		<p>Cuando se produzcan cambios significativos en la presente Política de Cookies, se comunicarán
		a los Usuarios bien mediante el sitio web o a través de correo electrónico a los Usuarios
		registrados.</p>
	',
];