<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ERROR_IMPORT_TITLE'            => 'Import errors',
    'FILE_NOT_UPLOADED_CORRECTLY'   => 'File not uploaded correctly',
    'FILE_TYPE_NOT_CSV'             => 'Uploaded file is not CSV file',
    'NO_SOURCE_URL_ALERT'           => 'You have not entered URL of your Magento shop. Images will not be uploaded. Are you sure to continue?',
    'IMPORT_WORKS'                  => 'Import works',
    'IMPORT_WORKS_TITLE'            => 'Import works',
    'IMPORT_SOURCE'                 => 'Import source',
    'IMPORT_LANGUAGE'               => 'Import language',
    'CSV_FILE'                      => 'CSV file',
    'UPLOAD_FILE'                   => 'Upload file',
    'IMPORT_SUBMIT'                 => 'Import',
    'IMPORT_LANG_ENGLISH'           => 'English',
    'IMPORT_LANG_SPANISH'           => 'Spanish',
    'SOURCE_SHOP_URL'               => 'Source shop main page url',
    'IMPORT_SUCCESS'                => 'Products have been imported successfully',
    'IMPORT_SUCCESS_WITH_WARNINGS'  => 'Products have been imported with problems',
    'IMPORT_ERROR'                  => 'Products not have been imported successfully. Please check your export file format and try again',
    'FLASH_TITLE_IMPORTED'          => 'Imported!',
    'FLASH_TITLE_ERROR'             => 'Error!',

    // Warnings

    'WARNING_IMAGE_UNREACHABLE'     => 'Image is unreachable',
    'WARNING_HOST_UNREACHABLE'      => 'Given shop URL address is unreachable. Images are not uploaded',
];
