<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '+0034 645 234 234' => '',
    'Add new +' => '',
    'Add to cart' => '',
    'Because of time zones difference an agent can take up to 24 hours to reply to you message.' => '',
    'Become a deviser - Todevise' => '',
    'Boxes' => '',
    'Brand name' => '',
    'Characteristics' => '',
    'Click the button below to go to our profile' => '',
    'Comments' => '',
    'Contact us via phone, our customer service representative are here to help you.' => '',
    'Contact via Facebook' => '',
    'Contact via Message' => '',
    'Contact via Phone' => '',
    'Contact via Whatsapp' => '',
    'Description' => '',
    'Even products' => '',
    'Express' => '',
    'FAQ' => '',
    'Get marketing guidance and SEO/SEM optimization by or team of experts.' => '',
    'Grown your brand' => '',
    'Having your outlet store on Todevise opens your business to a world of opportunities. Reach new customers, upload products with ease, manage and track you sales efficiently.' => '',
    'Help & Faq' => '',
    'Just add this number to your phone´s contact list and start a conversation with us!' => '',
    'Link to portfolio' => '',
    'Link to video' => '',
    'More ecological' => '',
    'Most popular' => '',
    'Newest' => '',
    'Odd products' => '',
    'Optional' => '',
    'Personal Info' => '',
    'Phone number' => '',
    'Potential onsite and social media promotion of your work' => '',
    'Reach international customers who understand your philosophy and appreciate your work.' => '',
    'Request invitation' => '',
    'Save in a box' => '',
    'See our full FAQ' => '',
    'Share on' => '',
    'Size' => '',
    'Stories' => '',
    'TERM' => '',
    'TERMS' => '',
    'View all devisers' => '',
    'View works' => '',
    'We constantly strive for excellence, and for this reason an invitation is needed to register as a deviser' => '',
    'What do you create?' => '',
    'Work policies' => '',
    'Works' => '',
    'Works by {name} {surnames}' => '',
    'You can message us via Facebook. Our social media team will reply in less than 24 hours.' => '',
    'Your Work' => '',
    'Yourself' => '',
    'email' => '',
    'name' => '',
    'observations' => '',
    'stock' => '',
    '{days,plural,=0{No returns} =1{Money-back guarantee of # day} other{Money-back guarantee of # days}}.' => '',
    '{months,plural,=0{# No warranty} =1{# month warranty} other{# months warranty}}.' => '',
];
