<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ABOUT_PERSON_NAME' => 'About {person_name}',
    'ABOUT_US' => 'About us',
    'ALL_CATEGORIES' => 'All categories',
    'ALMOST_DONE_PERSON_NAME' => 'Almost done! {person_name}',
    'BECOME_A_DEVISER' => 'Become a deviser',
    'BILLINGS_AND_PAYMENTS' => 'Billings & Payments',
    'BOXES_BY_PERSON_NAME' => 'Boxes by {person_name}',
    'BOX_NAME_BY_PERSON_NAME' => '{box_name} by {person_name}',
    'CANCEL' => 'Cancel',
    'CART' => 'Cart',
    'CATEGORY_WORKS_BY_PERSON_NAME' => '{category_name} works by {person_name}',
    'CHECKOUT' => 'Checkout',
    'COMPLETE_PROFILE_PERSON_NAME' => 'Complete your profile! {person_name}',
    'CONFIRM' => 'Confirm',
    'CONNECT_WITH_DIFFERENT_STRIPE_ACCOUNT' => 'Connect with a different stripe account',
    'CONNECT_WITH_STRIPE' => 'Connect with stripe',
	'CONTACT_TITLE' => 'Contact us',
    'CREATE_AN_INFLUENCER_ACCOUNT' => 'Create an influencer account',
    'CREATE_A_DEVISER_ACCOUNT' => 'Create a deviser account',
    'CREATE_NEW_WORK_BY_PERSON_NAME' => 'Create new work by {person_name}',
    'DAYS' => 'Days',
    'DISCOVER_DEVISERS' => 'Discover devisers',
    'DISCOVER_INFLUENCERS' => 'Discover influencers',
    'EDIT_ABOUT_PERSON_NAME' => 'Edit about {person_name}',
    'EDIT_PERSON_NAME_FAQS' => 'Edit {person_name} faqs',
    'EDIT_PRESS_BY_PERSON_NAME' => 'Edit press by {person_name}',
    'EDIT_PRODUCT_BY_PERSON_NAME' => 'Edit {product_name} by {person_name}',
    'EDIT_STORY_BY_PERSON_NAME' => 'Edit story {story_title} by {person_name}',
    'EDIT_VIDEOS_BY_PERSON_NAME' => 'Edit videos by {person_name}',
    'EDIT_WORKS_BY_PERSON_NAME' => 'Edit works by {person_name}',
    'EXPLORE_BOXES' => 'Explore boxes',
    'INCORRECT_USERNAME_OR_PASSWORD' => 'Incorrect username or password',
    'INDEX_TITLE' => 'Todevise',
    'LANGUAGE' => 'Language',
    'LOVED_BY_PERSON_NAME' => 'Loved by {person_name}',
    'MONTHS' => 'Months',
    'NEW_STORY_BY_PERSON_NAME' => 'New story by {person_name}',
    'NONE' => 'None',
    'ORDERS' => 'Orders',
    'ORDER_ID_COMPLETED' => 'Order {order_id} completed',
    'PAYMENTS_MADE_TROUGH_STRIPE' => 'All the payments on Todevise are made through Stripe, a payment processing platform. We use Stripe because it is very secure, fast and easy to use. The Stripe commission is 1,40% + 0,25€ for each transaction. The money will be transfered to your Stripe account immediately after each purchase. <br /><br/>To start selling on Todevise, you must open a Stripe account (it’s 100% free) and connect it to your Todevise profile. To do so, press the button below. When you finish creating your Stripe account, you will be redirected back to this page.',
    'PERSON_NAME_FAQS' => '{person_name} faqs',
    'PRESS_BY_PERSON_NAME' => 'Press by {person_name}',
    'PRODUCT_BY_PERSON_NAME' => '{product_name} by {person_name}',
    'PROFILE_AND_STRIPE_LINKED_INFO' => 'Your Todevise profile and Stripe account are now linked. Do you want to connect your profile to a different Stripe account? Press the button below.',
    'SELECT_CATEGORY' => 'Select category',
    'SELECT_COUNTRY' => 'Select country',
    'SELECT_METRIC_UNIT' => 'Select metric unit',
    'SETTINGS' => 'Settings',
    'SHIPPING_SETTINGS' => 'Shipping settings',
    'SIGNUP' => 'Signup',
    'STORIES' => 'Stories',
    'STORY_BY_PERSON_NAME' => 'Stories {person_name}',
    'VIDEOS_BY_PERSON_NAME' => 'Videos by {person_name}',
    'WEEKS' => 'Weeks',
    'WORKS' => 'Works',
    'WORKS_BY_PERSON_NAME' => 'Works by {person_name}',
    'WORKS_SEARCH_PARAM' => 'Works - {search_param}',
];
