<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'TITLE' => 'Returns and warranties',

	'BLOCK_1_TITLE' => 'Get to know the shipping and returns policies before purchasing',
	'BLOCK_1_TEXT_1' => 'You can find this information on the product’s page, under the SHIPPING & POLICIES section.',
	'BLOCK_1_TEXT_2' => 'All the devisers on Todevise manage their profiles and store themselves, and they have the freedom to decide their shipping, warranty and returns policy.',

	'BLOCK_2_TITLE' => 'Returning an item',
	'BLOCK_2_TEXT_1' => '&nbsp',
	'BLOCK_2_TEXT_2' => 'Before initiating the return process, we advise you to talk with the deviser through our CHAT system and get the following information:',
	'BLOCK_2_TEXT_3' => '<ul><li><p>/ a confirmation that they will accept the return</p></li><li><p>/ the return address</p></li><li><p>/ an agreement determining who will cover the costs of the return shipping</p></li></ul>',

	'BLOCK_3_TITLE' => 'Further issues',
	'BLOCK_3_TEXT_1' => 'If you cannot reach an agreement with the deviser, or you encounter any problem, please contact our customer support department <a href="{contact_link}"><strong>here</strong></a>.',

];
