<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	'TITLE' => 'Términos y condiciones',
	'TEXT' =>
		'
		<p>Las presentes Condiciones generales de uso y contratación (en adelante, Condiciones) regulan el uso y acceso al sitio web todevise.com (en adelante, la Plataforma), titularidad de TESSARACTIC, SL (en adelante, Todevise) para los usuarios de la Plataforma (en adelante, Usuario o Usuarios) así como la relación contractual de compra venta durante el proceso de compra de productos ofrecidos a través de la Plataforma.</p>
		<p>La Plataforma permite a los Usuarios descubrir y adquirir diferentes productos ofrecidos por comerciantes adheridos a la Plataforma que ofertan sus productos a través de esta (en adelante, los Devisers).</p> 
		<p>El acceso a la Plataforma implica el conocimiento y la aceptación de las presentes Condiciones así como tener la mayoría de edad y encontrarse en plenas facultades mentales para la posibilidad de adquirir cualquiera de los productos disponibles a través de la Plataforma.</p>
		
		<br />
		<b>Acceso y Registro</b>
		
		<p>Para poder ser Usuario de Plataforma es indispensable que se cumplan los siguientes requisitos:</p>
		<p> - Haber cumplido o ser mayor de 18 años de edad.</p>
		<p> - Cumplimentar de manera veraz los campos obligatorios del formulario de registro, en el que se solicitan datos de carácter personal:</p>
		<p> - nombre y apellidos;</p>
		<p> - su dirección de correo electrónico personal, su año de nacimiento y su dirección postal;</p>
		<p> - otros datos necesarios para operar que sean requeridos en la Plataforma;</p>
		<p></p>
		<p>El Usuario recibirá un mensaje de confirmación de activación de la cuenta en la dirección de correo electrónico indicada. Dicho mensaje contendrá su dirección de correo electrónico (identificador de usuario) y su contraseña para que pueda conectarse a la Plataforma.</p>
		<p>El Usuario garantiza que todos los datos sobre su identidad y legitimidad facilitados a la Todevise en sus formularios de registro de la Plataforma son veraces, exactos y completos. Asimismo se compromete a mantener actualizados sus datos. En el supuesto de que el Usuario facilite cualquier dato falso, inexacto o incompleto o si Todevise considera que existen motivos fundados para dudar sobre la veracidad, exactitud e integridad de los mismos, la Todevise podrá denegarle el acceso y uso presente o futuro de Plataforma o de cualquiera de sus contenidos y/o servicios.</p>
		<p>Al darse de alta en la Plataforma, el Usuario deberá introducir su nombre completo, un e-mail como identificador de usuario y seleccionar una clave de acceso (password). El password será estrictamente confidencial, personal e intransferible. El Usuario se compromete a no divulgar los datos relativos a su cuenta ni hacerlos accesibles a terceros. El Usuario será el único responsable en caso de uso de dichos datos por terceros, incluidas las manifestaciones vertidas en Plataforma, o cualquier otra actuación que se lleve a cabo mediante el uso de su username y/o password.</p>
		<p>Todevise permite el registro en Plataforma mediante la sincronización con servicios de terceros (Ej. Log-In con cuenta de Facebook). Todevise solicitará siempre al Usuario el consentimiento de forma previa al registro para la sincronización de servicios entre un tercero y Todevise</p>
		
		<br />
		<b>Obligaciones del Usuario</b>
		<p>El Usuario es responsable de contar con los servicios y equipos necesarios para la navegación por Internet y para acceder a la Plataforma. En caso de cualquier incidencia o dificultad para acceder al Plataforma, el Usuario puede informarlo a Todevise que procederá a analizar la incidencia y dará indicaciones al Usuario acerca de cómo resolverla en el plazo más breve posible.</p>
		<p>El Usuario es completamente responsable del acceso y correcto uso de la Plataforma y de sus contenidos y servicios con sujeción a la legalidad vigente, sea nacional o internacional, así como a los principios de buena fe, a la moral, buenas costumbres y orden público. Y específicamente, adquiere el compromiso de observar diligentemente las presentes Condiciones.</p>
		<p>Los Usuarios se abstendrán de usar la Plataforma con fines o efectos ilícitos y que sean lesivos de los derechos e intereses de terceros, o que de cualquier forma puedan dañar, inutilizar, afectar o deteriorar la Plataforma, sus contenidos y sus servicios. Asimismo, queda prohibido impedir la normal utilización o disfrute de la Plataforma a otros Usuarios.</p>
		<p>Todevise no podrá ser considerada responsable editorial, y declara expresamente que no se identifica con ninguna de las opiniones que puedan emitir los Usuarios de la Plataforma, especialmente de todas aquellas opiniones vertidas por los Usuarios con respecto a las características y cualidades de los productos ofrecidos desde la Plataforma, de cuyas consecuencias se hace enteramente responsable el emisor de las mismas.</p>
		<p>Quienes incumplan tales obligaciones, responderán de cualesquier perjuicio o daño que ocasionen. Todevise no responderá de ninguna consecuencia, daño o perjuicio que pudieran derivarse de dicho acceso o uso ilícito por parte de terceros.</p>
		<p>En general, el Usuario se compromete, a título enunciativo y no taxativo, a:</p>
		<p> - No utilizar la Plataforma para fines ilegales o no autorizados;</p>
		<p> - No alojar, almacenar, divulgar, publicar, distribuir o compartir cualquier contenido que pueda suponer una intromisión ilegítima o vulneración en cualquier forma de los derechos fundamentarles al honor, imagen e intimidad personal y familiar de terceros y, muy especialmente, de los menores de edad;</p>
		<p> - No publicar en ningún apartado de la Plataforma ni en su perfil o el de otro Usuario ningún comentario o información que sea ilegal, racista, xenófoba, obscena, pornográfica, abusiva, difamatoria, engañosa, fraudulenta o de cualquier forma contraria a la moral o al orden público;</p>
		<p> - No alterar o modificar, total o parcialmente la Plataforma, eludiendo, desactivando o manipulando de cualquier otra las funciones o servicios de la misma;</p> 
		<p> - No infringir los derechos de propiedad industrial e intelectual o las normas reguladoras de la  protección de datos de carácter personal;</p>
		<p> - No usar la Plataforma para injuriar, difamar, intimidar, violar la propia imagen o acosar a otros Usuarios;</p> 
		<p> - No acceder a las cuentas de correo electrónico de otros Usuarios;</p>
		<p> - No introducir virus informáticos, archivos defectuosos, o cualquier otro programa informático que pueda provocar daños o alteraciones en los contenidos o sistemas de Todevise o terceras personas;</p>
		<p> - No remitir correos electrónicos con carácter masivo y/o repetitivo a una pluralidad de personas, ni enviar direcciones de correo electrónico de terceros sin su consentimiento;</p> 
		<p> - No realizar acciones publicitarias de bienes o servicios sin el previo consentimiento de Todevise.</p>
		<p>Cualquier Usuario podrá reportar a otro Usuario cuando considere que está incumpliendo las presentes Condiciones, asimismo todos los Usuarios pueden informar a Todevise de cualquier abuso o vulneración de las presentes condiciones, a través del correo electrónico  general de contacto.  Todevise verificará este reporte, a la mayor brevedad posible, y adoptará las medidas que considere oportunas, reservándose el derecho a retirar y/o suspender a cualquier Usuario de la Plataforma por el incumplimiento de las presentes Condiciones. Asimismo Todevise se reserva el derecho a retirar y/o suspender cualquier mensaje con contenido ilegal u ofensivo, sin necesidad de previo aviso o posterior notificación.</p>
		
		<br />
		<b>Responsabilidad de Todevise</b> 
		<p>Todevise no controla ni será responsable de los contenidos vertidos por los Usuarios a través de la Plataforma, siendo estos los únicos responsables de la adecuación legal de dichos contenidos.</p>
		<p>Todevise no tiene obligación de controlar y no controla la utilización que los Usuarios hacen de la Plataforma y, por consiguiente, no garantiza que los Usuarios utilicen la Plataforma de conformidad con lo establecido en las presentes Condiciones, ni que hagan un uso diligente y/o prudente de la misma. Todevise no tiene la obligación de verificar y no verifica la identidad de los Usuarios, ni la veracidad, vigencia, exhaustividad y/o autenticidad de los datos que los mismos proporcionan.</p>
		<p>Todevise excluye cualquier responsabilidad por los daños y perjuicios de toda naturaleza que pudieran deberse a la utilización ilícita de la Plataforma por parte de los Usuarios o que puedan deberse a la falta de veracidad, vigencia, exhaustividad y/o autenticidad de la información que los Usuarios proporcionan a otros Usuarios.</p>
		<p>Sin perjuicio de lo anterior, Todevise se reserva la facultad de limitar, total o parcialmente, el acceso a la Plataforma a determinados Usuarios, así como de cancelar, suspender, bloquear o eliminar determinado tipo de contenidos, mediante la utilización de instrumentos tecnológicos aptos al efecto, si tuviese conocimiento efectivo de que la actividad o la información almacenada es ilícita o de que lesiona bienes o derechos de un tercero. En este sentido, Todevise podrá establecer los filtros necesarios a fin de evitar que a través del servicio puedan verterse en la red contenidos ilícitos o nocivos.</p>
		<p>Todevise no responderá en caso de interrupciones del servicio, errores de conexión, falta de disponibilidad o deficiencias en el servicio de acceso a Internet, ni por interrupciones de la red de Internet o por cualquier otra razón ajena a su control.</p>
		<p>Todevise no se hace responsable de los errores de seguridad que se puedan producir ni de los daños que puedan causarse al sistema informático del Usuario (hardware y software),  a los ficheros o documentos almacenados en el mismo, como consecuencia la presencia de un virus en el sistema informático o terminal móvil del Usuario que sea utilizado para la conexión a los servicios y contenidos de la Plataforma.</p>
		
		<br />
		<b>Proceso de Compra</b>
		<p>El Usuario podrá acceder a la adquisición de los productos ofertados por los Devisers a través de la Plataforma introduciendo los datos solicitados en el correspondiente formulario de la pasarela de compra de la Plataforma. Posteriormente, el Usuario deberá seguir todos los pasos del procedimiento de compra que le marque la Plataforma.</p>
		<p>Las descripciones de los productos y servicios así como de sus precios que son ofertados a través de la Plataforma, se realizan estrictamente en base a la información y documentación proporcionada por los Devisers, por lo que Todevise no responderá frente a posibles inexactitudes en dichas descripciones.</p>
		<p>Los pagos a través de la Plataforma, se hacen a través de la pasarela de pago de Stripe (https://stripe.com) de forma integrada en la pasarela de compra de la Plataforma.</p>      
		<p>Asimismo la pasarela de compra de la Plataforma informará al Usuario, una vez finalizado el procedimiento de compra, vía correo electrónico, de todas las características relevantes del  producto adquirido. Si el Usuario no recibiese el mail de confirmación dentro de las veinticuatro horas siguientes a la finalización de la compra, será responsabilidad del Usuario confirmar con Todevise la aprobación de la transacción.</p>
		<p>Los precios de los productos ofertados en la Plataforma incluyen el Impuesto sobre el Valor Añadido (IVA) u otros impuestos que pudieran ser aplicables y en todo caso se expresarán en la moneda Euro (€).</p>
		<p>Los pedidos realizados en la Plataforma de Todevise se regirán por los precios ofertados de cada producto en el momento de realizar el pedido. Los precios aplicables serán los publicados de forma automática durante el proceso de compra en la última fase del mismo. El Usuario será siempre comunicado del precio final de compra de un producto de forma previa a la finalización de la pasarela de compra.</p>
		
		<br />
		<b>Envío de productos</b>
		<p>Los Devisers envían los pedidos directamente a los Usuarios a través de diferentes empresas de transporte. El precio de envío se calcula automáticamente en el momento de realizar un pedido y se calcula en base al peso de la orden y destino. Los plazos de entrega varían entre en función de la cantidad pedida, stock y destinación.</p>
		<p>En cualquier caso, los Devisers informarán de todas las características de sus envíos en las fichas de los productos ofertados en la Plataforma y en todo caso entregarán los productos a la dirección de envío indicada por el Usuario en el menor tiempo posible en cualquier caso, siempre dentro de los treinta (30) días naturales a partir de la fecha en que se realizó el pedido.</p>
		<p>Los pagos a los Devisers por la compra de productos conllevarán la emisión de una factura a nombre del Usuario según los datos facilitados durante la pasarela de compra. En caso de que el Usuario desee recibir la factura de la compra realizada, deberá solicitarla directamente al Deviser mediante la información de contacto facilitada por el Deviser a través de la Plataforma.</p>
		
		<br />
		<b>Derecho de desistimiento</b>
		<p>El Usuario dispondrá de un plazo de 14 días naturales para desistir en la compra de un producto contados a partir de la fecha de recepción del producto para la devolución del mismo. Salvo que la devolución sea realizada por defectos o mal estado en el producto, los gastos relativos a la devolución deberán ser asumidos por parte del Usuario y el producto deberá ser devuelto en perfectas condiciones sin limitar el uso del producto (siempre que no vaya más allá de la mera comprobación del buen estado y funcionamiento del mismo).</p>
		<p>Para tramitar la devolución del producto por desistimiento, el Usuario deberá ponerse en contacto con el Deviser y seguir sus instrucciones para la devolución. Una vez el Deviser reciba el producto y compruebe que se encuentra en perfectas condiciones, procederá a la devolución del importe del producto así como de los gastos de envío pagados por el Usuario en un plazo no superior a 14 días naturales.</p>
		<p>De acuerdo al artículo 103 del Real Decreto Legislativo 1/2007, de 16 de noviembre, por el que se aprueba el texto refundido de la Ley General para la Defensa de los Consumidores y Usuarios, no serán aptos para su desistimiento los productos adquiridos en la Plataforma que:</p>
		<p>Estén precintados y que no sean aptos para ser devueltos por razones de protección de la salud o higiene y que hayan sido desprecintados tras la entrega.</p>
		<p>Hayan sido personalizados conforme a las especificaciones del Usuario.</p>
		
		<br />
		<b>Garantía de los productos</b>
		<p>Asimismo los Devisers de la Plataforma responderán con una garantía en sus productos por las faltas de conformidad que se manifiesten por parte del Usuario durante el plazo de 2 años a contar desde el momento de la entrega del producto. En caso de que un producto esté defectuoso, el Deviser procederá, según corresponda, a la reparación, sustitución, rebaja o devolución del importe del producto, sin que suponga ningún coste adicional para el Usuario. El Usuario tendrá un plazo máximo de dos meses para informar al Deviser de la falta conformidad con el funcionamiento o la calidad de un producto a contar desde el momento en el que tenga conocimiento.</p>
		
		<br />
		<b>Condiciones de uso de las promociones</b>
		<p>Los Usuarios podrán aplicar cualquiera de los diferentes cupones promocionales para beneficiarse de las ofertas de Todevise existentes siempre que estos hayan sido expedidos o validados por Todevise y se encuentren dentro de su periodo de vigencia.</p>
		<p>Todos los cupones promocionales están limitados a único uso por Usuario. En concreto, los cupones promocionales estarán limitados a un único titular de medios de pago, cuenta y número de teléfono. Todevise se reserva el derecho de solicitar al Usuario documentación adicional en caso de que tenga sospechas de que se está produciendo una posible duplicidad de cuentas destinadas a beneficiar con una promoción a un mismo Usuario.</p>
		
		<br />
		<b>Actualización y modificación de la Plataforma</b>
		<p>Todevise podrá modificar las presentes Condiciones en cualquier momento mediante correo electrónico o publicando los términos modificados en la Plataforma. Todos los términos modificados entrarán en vigor automáticamente a los 30 días de haber sido publicados.
		<p>Asimismo, Todevise se reserva la facultad de efectuar, en cualquier momento y sin necesidad de previo aviso, actualizaciones, modificaciones o eliminación de información contenida en su Plataforma en la configuración y presentación de ésta y de las condiciones de acceso, sin asumir responsabilidad alguna por ello.
		
		<br />
		<b>Propiedad Intelectual</b>
		<p>Todevise es titular o licenciataria de los derechos de propiedad intelectual e industrial que recaen sobre los textos, fotografías, diseño gráfico, código fuente y todo el resto de contenido de la Plataforma protegido bajo las leyes de propiedad intelectual e industrial. Como consecuencia de ello corresponde a Todevise el ejercicio exclusivo de los derechos de explotación de los mismos en cualquier forma y, en especial, los derechos de reproducción, distribución, comunicación pública y transformación, de conformidad con la legislación española de derechos de propiedad intelectual e industrial.
		<p>La autorización al Usuario para el acceso a la Plataforma no supone renuncia, transmisión, licencia o cesión total ni parcial sobre derechos de propiedad intelectual o industrial por parte de Todevise.
		<p>No está permitido suprimir, eludir o manipular de ningún modo los contenidos de la Plataforma de Todevise. Asimismo está prohibido modificar, copiar, reutilizar, explotar, reproducir, comunicar públicamente, hacer segundas o posteriores publicaciones, cargar archivos, enviar por correo, transmitir, usar, tratar o distribuir de cualquier forma la totalidad o parte de los contenidos incluidos en la Plataforma de Todevise para propósitos públicos o comerciales, si no se cuenta con la autorización expresa y por escrito de Todevise o, en su caso, del titular de los derechos a que corresponda.
		<p>El Usuario que proceda a compartir cualquier tipo de contenido a través de la Plataforma, concede a  Todevise una licencia no exclusiva, gratuita y mundial limitada a la reproducción y comunicar públicamente dicho contenido a través de la prestación de los servicios de la Plataforma.
		
		<br />
		<b>Protección de datos</b>
		<p>Todevise manifiesta su compromiso de cumplir con la legislación vigente en cada momento en materia de protección de datos, concretamente con la Ley Orgánica 15/1999, de 13 de diciembre, de Protección de Datos de Carácter Personal; el Real Decreto 1720/2007, de 21 de diciembre, que aprueba el Reglamento de desarrollo de la Ley Orgánica 15/1999; el Reglamento (UE) 2016/679 del Parlamento Europeo y del Consejo, de 27 de abril de 2016, y demás legislación aplicable. De conformidad con el artículo 5 de la Ley 15/1999, de 13 de diciembre, de Protección de Datos de Carácter Personal, se informa a los Usuarios que los datos de carácter personal que sean facilitados en la Plataforma serán objeto de tratamiento automatizado y pasarán a formar parte de los ficheros titularidad de la Todevise, como responsable del ficheros debidamente inscrito en el Registro General de la Agencia Española de Protección de Datos, para las finalidades propias de gestión de Usuarios registrados en la Plataforma de Todevise.
		
		<br />
		<br />
		<b>Información básica sobre Protección de Datos</b>
		<div class="table-responsive">
			<table class="table">
				<tr>
					<td>Responsable del tratamiento</td>
					<td>TESSARACTIC, S.L.     NIF: B55136360</td>
				</tr>
				<tr>
					<td>Finalidad del tratamiento
					<td>Gestión y prestación de servicios solicitados</td>
				</tr>
				<tr>
					<td>Legitimación del tratamiento</td>
					<td>Cumplimentación de formularios Plataforma, Registro de usuarios y uso del Servicio.</td>
				</tr>
				<tr>
					<td>Destinatarios de cesiones o transferencias</td>
					<td>No se prevén cesiones de datos a terceras personas</td>
				</tr>
				<tr>
					<td>Derechos</td>
					<td>Acceder, rectificar y cancelar los datos, así como otros derechos, como se explica en la información adicional.</td>
				</tr>
			</table>
		</div>
		<p>Puede consultar información adicional y detallada en nuestra <a href="/privacy-policy">Política de Privacidad</a>.</p>
		
		<br />
		<b>Independencia de las Cláusulas</b>
		<p>Si cualquiera de las cláusulas de las presentes Condiciones fuera nula de pleno derecho o anulable, se tendrá por no puesta. Dicha declaración de nulidad no invalidará el resto de las Condiciones, que mantendrá su vigencia y eficacia entre las partes.</p>
		<p>Si cualquier cláusula de las presentes Condiciones fuese declarada, total o parcialmente, nula o ineficaz, tal nulidad o ineficacia afectará tan solo a dicha disposición o a la parte de la misma que resulte nula o ineficaz, y las Condiciones subsistirán en todo lo demás, teniéndose tal disposición o la parte de la misma que resulte afectada por no puesta.</p>
		
		<br />
		<b>Legislación Aplicable</b>
		<p>Las presentes Condiciones se regirán por la legislación española, que será de aplicación en lo no dispuesto en estas Condiciones en materia de interpretación, validez y ejecución. Asimismo ambas partes se someten, con renuncia expresa a cualquier otro fuero, a los Juzgados y Tribunales de Barcelona.</p>
		<p>La Comisión Europea pone a disposición de los consumidores de la Unión Europea la plataforma de resolución de litigios en línea para resolver los litigios que se produzcan en el comercio electrónico de forma amistosa (artículo 14 apartado 1 Reglamento (UE) 524/2013) por lo cual los Usuarios de la Plataforma tienen derecho presentar reclamaciones en el siguiente enlace: <a href="https://webgate.ec.europa.eu/odr/main/index.cfm?event=main.home.show&lng=ES">https://webgate.ec.europa.eu/odr/main/index.cfm?event=main.home.show&lng=ES</a></p>

	',
];